USE tomtroc;

INSERT INTO books (photo, title, author, description, is_available, user_id) VALUES
('uploads/books/naruto_tome_1.jpg', 'Naruto - Tome 1', 'Masashi Kishimoto', 'Naruto Uzumaki reve de devenir Hokage, le ninja le plus puissant de son village.', 1, 1),
('uploads/books/one_piece_tome_1.jpg', 'One Piece - Tome 1', 'Eiichiro Oda', 'Monkey D. Luffy part a la recherche du tresor legendaire, le One Piece, pour devenir le roi des pirates.', 0, 2),
('uploads/books/attack_on_titan_tome_1.jpg', 'L\'Attaque des Titans - Tome 1', 'Hajime Isayama', 'L\'humanite vit recluse derriere des murs pour se proteger de creatures geantes appelees Titans.', 1, 2),
('uploads/books/harry_potter_1.jpg', 'Harry Potter a l\'ecole des sorciers', 'J.K. Rowling', 'Harry decouvre qu\'il est sorcier et entre a l\'ecole de Poudlard, ou il se lie d\'amitie avec Ron et Hermione.', 1, 3),
('uploads/books/seigneur_anneaux_1.jpg', 'La Communaute de l\'Anneau', 'J.R.R. Tolkien', 'Frodon Sacquet herite d\'un anneau aux pouvoirs immenses et dangereux, qu\'il doit detruire pour sauver la Terre du Milieu.\n\nFrodon Sacquet herite d\'un anneau aux pouvoirs immenses et dangereux, qu\'il doit detruire pour sauver la Terre du Milieu.', 0, 3),
('uploads/books/1984.jpg', '1984', 'George Orwell', 'Dans un monde totalitaire, la population est constamment surveillee par Big Brother.\n\nDans un monde totalitaire, la population est constamment surveillee par Big Brother.\n\nDans un monde totalitaire, la population est constamment surveillee par Big Brother.\n\nDans un monde totalitaire, la population est constamment surveillee par Big Brother.', 0, 4),
('uploads/books/le_petit_prince.jpg', 'Le Petit Prince', 'Antoine de Saint-Exupery', 'Un conte poetique et philosophique sur l\'amitie, l\'amour et le sens de la vie.\n\nUn conte poetique et philosophique sur l\'amitie, l\'amour et le sens de la vie.\n\nUn conte poetique et philosophique sur l\'amitie, l\'amour et le sens de la vie.\n\nUn conte poetique et philosophique sur l\'amitie, l\'amour et le sens de la vie.\n\nUn conte poetique et philosophique sur l\'amitie, l\'amour et le sens de la vie.\n\nUn conte poetique et philosophique sur l\'amitie, l\'amour et le sens de la vie.\n\nUn conte poetique et philosophique sur l\'amitie, l\'amour et le sens de la vie.', 1, 4);
